source 'https://github.com/shopping1985/ZDSpec.git'
use_frameworks!
platform :ios, '10.0'

target 'ZDUIComponent_Example' do
  pod 'ZDUIComponent', :path => '../'

  target 'ZDUIComponent_Tests' do
    inherit! :search_paths

    
  end
end
